### ISSUE TITLE
is there auto connection ?

### ISSUE THREAD

**Issue by pranavlathigara** [douglasjunior/AndroidBluetoothLibrary#1]
Hi
Thank you for this Library 
I have question about this Library 
Is there any option for auto connection for Specific Device after Loss Connection ?

**Comment by douglasjunior** [comment]
The library does not, but you can do it easily. Something like:

```java
    @Override
    public void onStatusChange(BluetoothStatus status) {
         if (lastStatus == BluetoothStatus.CONNECTED && status == BluetoothStatus.NONE) {
              mService.connect(device);
         }
         lastStatus = status;
    }
```

You can also open a dialog indicating that you are reconnecting, etc.

**Comment by douglasjunior** [comment]
You can also connect to a device knowing your mac.

```java
BluetoothDevice device = mBluetoothAdapter.getRemoteDevice(macAddress);
mService.connect(device);
```

**Comment by pranavlathigara** [comment]
yes this is nice but once i lost connection or out of range with specific device and then come to range it gets auto connect with that device 
is it possible..?

**Comment by douglasjunior** [comment]
Yes, you can create a service that keeps trying to connect again.

**Comment by douglasjunior** [comment]
Please, if you have no further questions, you can close the issue. 😄
