### ISSUE TITLE
writeCharacteristic always returning false 

### ISSUE THREAD

**Issue by carlastabile** [douglasjunior/AndroidBluetoothLibrary#10]
Hi. I'm trying to write using your lib but on the logs I can see that the method writeCharacteristic is always returning false. I've been looking on the internet and it may have something to do with multiple gatt operations? I'm not sure, I have to write and read multiple times but it fails even on the first time

I'm writing like this

```
if (mService != null) {
            BluetoothWriter writer = new BluetoothWriter(mService);
            writer.writeln(msg+"\n");
            Log.d(TAG, "Writting: " + msg);
}
```

**Comment by douglasjunior** [comment]
First you need to make sure that you have selected the correct UUID for the `service` and for the `characteristic`. Then, you can `write` after the connection has been established successfully.

You can use this apps to help to find the UUIDs:

- https://play.google.com/store/apps/details?id=uk.co.alt236.btlescan
- https://play.google.com/store/apps/details?id=com.edodm85.bluetoothbleterminal.free
