### ISSUE TITLE
make the buffering using characterDelimiter optional when receiving data

### ISSUE THREAD

**Issue by darkrift** [douglasjunior/AndroidBluetoothLibrary#13]
The characterDelimiter feature prevents some protocol to actually be implemented if a message payload is defined by a different mean than delimiter at the end (for instance the first 2 received bytes could define the payload length).

If the "buffering" was part of the react native application instead of being in the bluetooth bridge, that would open up a whole new set of possibilities.

This actually prevent me from receiving a message from my body scale that doesn't have a character delimiter at the end of it's messages...

**Comment by douglasjunior** [comment]
> The characterDelimiter feature prevents some protocol to actually be implemented if a message payload is defined by a different mean than delimiter at the end (for instance the first 2 received bytes could define the payload length).

Without a characterDelimiter the user need to control the messages start/end manually. In this case the library is useless.

> If the "buffering" was part of the react native application instead of being in the bluetooth bridge, that would open up a whole new set of possibilities.

This library was created before React Native exists, portability came later. So, the buffering is a second option if you cant use a characterDelimiter, but is hard to work with it.

Why can not you use buffering today?
