### ISSUE TITLE
Multiple characteristics per single service

### ISSUE THREAD

**Issue by senomis** [douglasjunior/AndroidBluetoothLibrary#16]
I would like to use your AndroidBluetoothLibrary (the BLE implementation) in one personal project and I'm wondering how to setup a service with multiple characteristics. From the sample code it looks like it's possible to pass only one characteristic per service.

**Comment by douglasjunior** [comment]
Today is not possible.

**Comment by Smbat888** [comment]
Hey,
I really need your help Douglas.
Can you help me to have multiple characteristics support for single service instance?

Thanks in advance.

**Comment by douglasjunior** [comment]
The library was not created for this purpose. This change would generate a lot of workload and I do not have time to implement it now. 😕
