### ISSUE TITLE
Reading on demand.

### ISSUE THREAD

**Issue by sswxyz17** [douglasjunior/AndroidBluetoothLibrary#20]
Hello, sorry if this is a stupid question but I was wondering if there is a way to read from a peripheral device on demand, like for example when I press a button or something else? As far as I understand you can read when a device writes to you, but I was still wondering if there is another way to read.
Thank you in advance.

**Comment by douglasjunior** [comment]
The remote device needs to write something for you to read.

You can write something to the remote device, and then the remote device read the message and writes something back.

**Comment by ederdoski** [comment]
Hello, If I wanted to read on demand, would not there be any solution that does not include writing to the device?

**Comment by jjrodcast** [comment]
@ederdoski you mean that you want to read when you fires an action? If that's the case I think you have to send the corresponding data to other devices.

**Comment by jjrodcast** [comment]
@ederdoski it is simple, when you want to read data there is an interface  where you can read the bytes the same if you want to send data to other device.
