### ISSUE TITLE
Bluetooth disconnect from device when app closes

### ISSUE THREAD

**Issue by gilgoldzweig** [douglasjunior/AndroidBluetoothLibrary#21]
The service disconnect without giving the option to control when to disconnect the device.

There is no way for me to override when you disconnect from the device.

**Comment by douglasjunior** [comment]
This is a default bluetooth behavior, it is not the library that decides this.

**Comment by gilgoldzweig** [comment]
How can I change it so that the device will not disconnect when the app close?

**Comment by douglasjunior** [comment]
Something like 
https://stackoverflow.com/questions/25267753/how-to-keep-bluetooth-connection-in-background

**Comment by gilgoldzweig** [comment]
I have a service that is running in the background but how can I let the service lifecycle control the BluetoothService lifecycle?

**Comment by jjrodcast** [comment]
I think the service disconnect when you resume or pause your app, probably you have to make your own implementation unless I am wrong.
