### ISSUE TITLE
bufferArray & characterDelimiter

### ISSUE THREAD

**Issue by muhammedgunes** [douglasjunior/AndroidBluetoothLibrary#22]
I try to connect to bluetooth kitchen scale. Scale send data like this:

[Condition]+[sp]+[Weight] + [Unit]+[sp]+[sp]+[Checksum] +[CR]+[LF]
(Total 16 Characters. The instrument sends the package continuously)

How can i find and set correct buffer size or correct characterDelimiter.

**Comment by douglasjunior** [comment]
You need to find a pattern in communication. I believe that in your case, the buffer does not help.

Could you show a 10 real amount of data received?
