### ISSUE TITLE
Bluetooth Device Connection Without Pairing Passcode

### ISSUE THREAD

**Issue by AnkurJagani** [douglasjunior/AndroidBluetoothLibrary#23]
Can we connect to the Bluetooth device (e.g. Health Device, Wireless EarPhone etc etc.) without entering any pairing passcode with this library?

For example, I need to connect to this [device](http://cooey.co.in/bluetooth_body_analyser.html) without entering any pairing code for the first time or anytime.

This device has their own application and it is capable to connect automatically when the device is in range. So I know this thing is possible but don't know how to do this.

Is this library capable to connect like the flow I have mentioned above?

Thank you very much for your help in advance.

**Comment by douglasjunior** [comment]
This library is just a bridge to the bluetooth API, if is possible to connect directly via bluetooth API, then is possible to connect with the library.
