### ISSUE TITLE
Client/Server Architecture?

### ISSUE THREAD

**Issue by salocinx** [douglasjunior/AndroidBluetoothLibrary#31]
Hi. Can I somehow connect to multiple Bluetooth devices simultaneously with library? I basically want to connect several Bluetooth clients to one Bluetooth server. Or can the `BluetoothService` object only handle one connection at a time?

**Comment by jjrodcast** [comment]
- I think that this library works one to one connection.

**Comment by jaswant-iotric** [comment]
No, it doesn't support BLE (Bluetooth Low energy) so it can only work with one-one connections.
