### ISSUE TITLE
Does not work connect to device

### ISSUE THREAD

**Issue by daimonkor** [douglasjunior/AndroidBluetoothLibrary#32]
I can not connect two devices (current sample kotlin).
http://prntscr.com/m12p6r

Tested https://github.com/ybenannoune/BluetoothPong works normal (used classic https://github.com/googlesamples/android-BluetoothChat/blob/master/Application/src/main/java/com/example/android/bluetoothchat/BluetoothChatService.java )
Thanks for help.

**Comment by jjrodcast** [comment]
I think that currently the library just support to connect one device. @douglasjunior could give you more details about that

**Comment by daimonkor** [comment]
> 
> 
> I think that currently the library just support to connect one device. @douglasjunior could give you more details about that

Yes, I tested server/client devices, can not connect

**Comment by douglasjunior** [comment]
@jjrodcast is right. The library was created to connect to devices like thermal printers, arduino, and others devices serial communication.

**Comment by daimonkor** [comment]
ok, step by step:
1. compile and install sample kotlin on first device
2. compile and install sample kotlin on second device
3. start application at both devices
4. start scan on first device
5. turn to connect to my found device and shown toast with "NONE" message.

I used classic bluetooth service class, I found it is the same with bluetooth chat class and the same with my tested ap (ping pong). But ping pong network part works, current library does not work.

**Comment by douglasjunior** [comment]
This is the problem, this library will not work with two smartphones, because this library not work in "server mode", only in "client mode".

**Comment by daimonkor** [comment]
I am trying only connect two devices, classic scenario. I think that BluetoothClassicService.class confirm my idea.

**Comment by GPla** [comment]
> This is the problem, this library will not work with two smartphones, because this library not work in "server mode", only in "client mode".

It would be nice, if you could add that to the project description.
