### ISSUE TITLE
How to read using the classic bluetooth?

### ISSUE THREAD

**Issue by michaelboeding** [douglasjunior/AndroidBluetoothLibrary#40]
How do I read using the classic bluetooth? Not seeing anything in the documentation. Thanks

**Comment by douglasjunior** [comment]
You should use the `setOnEventCallback` and then `onDataRead`.

[Sample project](https://github.com/douglasjunior/AndroidBluetoothLibrary/blob/5b9061b7eb02fab3126e91621cedfaa0f7d8a28c/Sample/src/main/java/com/github/douglasjunior/bluetoothsample/MainActivity.java#L154).

**Comment by michaelboeding** [comment]
Thanks for the quick reply! Im pretty new to Android/Java I have that implemented in my code but how do I get that to call. 

Like for example I use service.write(byteArray[]) to write to the bluetooth device which in turn calls the onDataWrite(). Is there a similar way to call the read? Or how would I do that?

Thanks again, really appreciate it.

**Comment by douglasjunior** [comment]
You need to read more about Bluetooth and asynchronous programming.

Receiving data via bluetooth is asynchronous, so there is no method for reading synchronously.

**Comment by michaelboeding** [comment]
Just did some reading and I see. I am running BLE(can't seem to use BLE on the android version because the bluetooth module has a bug) on my IOS version of the app I'm working on so I was thinking it was setup like that, where I would read whenever I needed a value. It's just weird that I'm not receiving any data from the callback, since the device should be sending data constantly when connected. Will do some more digging, thanks.
