### ISSUE TITLE
OnDataRead() not fired

### ISSUE THREAD

**Issue by vdhaimo** [douglasjunior/AndroidBluetoothLibrary#49]
`onDataRead(buffer: ByteArray, length: Int)` is not fired for BLE device

**Comment by douglasjunior** [comment]
`onDataRead` is fired when `bufferSize` or `characterDelimiter` are reached.

We have several issues explaining how it works here.

- https://github.com/douglasjunior/AndroidBluetoothLibrary/issues/41
- https://github.com/douglasjunior/AndroidBluetoothLibrary/issues/22
- https://github.com/douglasjunior/AndroidBluetoothLibrary/issues/5
